language: go
os: linux
dist: xenial
group: stable
sudo: required

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    # SDK Tools Revision 26.1.1
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip
    # For Updates check https://developer.android.com/studio#downloads
    - GOFLAGS=-mod=vendor
    - GO111MODULE=on
    - secure: maRHPJPVUD2QtOi9nuLWiXaB++TytQ2J3JSMyz0FU0wh/7gsvGzGQksbDMAjatX1b5lotoqaTAwvXwPWv4F+IuMZNUZfdS6/KVfOQjchJJTfduZoqT/bAWJTfAG8gwYST1rkqgwdCEPM4sXwVdjudqNOIDPsyZLopWilYXX5WUTURyQtf2+GZlJs/HT1ovp/DtRgK5m+RVxMZ60HLQjimxib+sDYRYTpf7psrkXHc5NMHCzjI5WCja2YoE8NRf3EKtWcOOLRLqum0zbzcmygvvxKTjMhXkcrc+rhbiYgB/JIdgB9Ft6ZKaoienh4Cfau5wTJ9HiAt3MBQp56tPTe83EoWI3sjAhDYGLxe6zWhsEl/wJ1YzQmO5Z/nuJcgP3XawHd/G0s64i9Ildz02zt4UKWcPCDPZSruit4GcjxjpWIApMzkrDNrDS7x3zBnpJID//c31B4+CU5TfPABn/u3NAA9OfHIVjs7DxQ4qoJFyRE72PAE01Jti1YaHYAgJLekwq3t85aP6uETCxdS1fBdkKs4EZf7nhzT7gXTzZKAY24kqBprktFOTPBU81y2iJvPk6aqWZrkjOgRGN9MmzLuOXJr6rieuVZ6zpvQakaHfodPnMyVUeSPYPrANlgT6mHOZOH/a7SWAI+VqPF9c05MkeCTRpHx/8rDLJjTCY0msw=
    - secure: jjQ821j4XeIn7BQ8ZqLvqTHZ1VhDo9oKbPpWtu8Qda7vBCvVR6bVEZNOAjZSXuyChfLi81ZAvXSBy2LS7Z5rL7oRcaB4BIEV9dH+PJBsn6k6aDYqvkJ5Mb2+1KzN/n7mVw8JWbjH4cXPzoug182TJ94+9RGrjlLA48aSgjN7AInv0yLgguzQVMf3hNGhRQ3tZfes8FjJ+xaXgWzRLOf8lloyEG33H4j7qVNWD6f2mptRqEu27L7lZWyjBkABKaRpLkLmCf5Z2O/zi3P5Z7OGCEwQnL/pEdzTZmhkVSioKhV1RM3hyc9aieamOfweapZEH0E9p7oT8jJQh2gL4JCov9G8JLgauM1gC1Q09KXkFi41yPndTpyq5lBaDgXH4hnBim41Jiv4MSooT9PcEHGzFFnLJVAIBMCHGPM9lr8Z8MmUt0cQsa41ujW+6C7wkE4boghosJFeS5YS8caMTZi0UtZ4ftD7K/fir12fagQyR1mz0eImzj3oJe9MwMDpqr9+pBfc+JIGoTCwukLWd7+Cz4qfea/iiOzhVZl6NzKnwgWYOm+6Wb46No6Ib2N5a8f9ft0QMUK54MTeRPcCMTnbBtQ1Ct5A56+dLAgUV4LV/JuEbrx+NNwlh0mi/V8+3hTdB2+jHET5Uoh7R+i8B2NcfcR5rI3BmCqkDBWCe4cQDg0=

go:
  - "1.12.x"

before_install:
  # check if OpenJDK8 is installed and install if missing
  - if ! dpkg -s openjdk-8-jdk >/dev/null 2>&1; then sudo apt-get update; sudo apt-get install openjdk-8-jdk; fi
  - java -version
  # print available java versions with their path (must contain java-8-openjdk-amd64)
  - sudo update-alternatives --config java
  # set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # download und unzip Android SDK Tools
  - wget https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  # set SDK Tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

install:
  # latest SDK Platform-Tools
  - yes | sdkmanager "platform-tools" >/dev/null
  # defined SDK Platform
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL" >/dev/null
  # defined SDK Build-Tools
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" >/dev/null
  # list installed and available packages
  - sdkmanager --list

  # This script is used by the Travis build to install a cookie for
  # go.googlesource.com so rate limits are higher when using `go get` to fetch
  # packages that live there.
  # See: https://github.com/golang/go/issues/12933
  - bash scripts/gogetcookie.sh
  - make tools

git:
  depth: 1

before_script:
  - pyenv global system 3.7
  - pip3 install gmsaas
  - gmsaas auth login $GENYMOTION_EMAIL $GENYMOTION_PASSWORD
  - gmsaas config set android-sdk-path $ANDROID_HOME

script:
  - make lint
  - make testacc

branches:
  only:
    - /.*/
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
